### ISSUE TITLE
Potential issue @ line 393

### ISSUE THREAD

**Issue by DKrzewinski** [wsowe2/Public#1]
Line 393 is reporting an error as we are using Get-ADComputer and passing an object instead of name.
Current line is:
Enabled = (Get-ADComputer $Computer -Properties enabled | select enabled).enabled
Should it not be changed to the below?
Enabled = (Get-ADComputer $Computer.Name -Properties enabled | select enabled).enabled

**Comment by wsowe2** [comment]
line 370: the $Computer variable should be the full computer object from line 352. You shouldn't have to pass the name parameter to do a get-adcomputer on the computer object. if it is erroring for you, you can change it to the name parameter, but it should work as written.

**Comment by DKrzewinski** [comment]
I see, well for me personally changing like 393 as stated above removed the issue.
Thanks!
