### ISSUE TITLE
Error in line 78 - null valued expression

### ISSUE THREAD

**Issue by DKrzewinski** [wsowe2/Public#2]
Line 78 seems to report an issue for null-valued expression:

You cannot call a method on a null-valued expression.
At C:\Tombstone\Secure\Tombstoning.ps1:78 char:2
+     $LoggingCSV.Add($Add)
+     ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Could you please confirm why this is happening?

**Comment by wsowe2** [comment]
If you didn't copy the empty Logging CSV from the zip into the corresponding folder (line 24 sets the location) then the file doesn;t exist yet. if it is empty, you may need to add something meaningless in the first line so it has something to actually import. it is just tied to that file being either empty or non-existent.

**Comment by DKrzewinski** [comment]
I've copied the DailyCleanup.csv file as suggested and tried again.
Looks like the script removed the old daily files and creates new ones, but the DailyCleanup.csv file is not re-created (just deleted), which than throws this error.
Are you suggesting to add any random data to it so it is re-created?

**Comment by wsowe2** [comment]
I am not talking about any of the "Daily" files, but the Tombstone.csv file that is used to log the info for tombstoned objects. if that file doesn't exist or isn't loaded (lines 24 and 28) then it will give you that error. i am not sure if it will give the error if the file is empty or not, i had populated it when i created the script. if it exists and is loading but it is throwing that error due to it being empty, add a generic line with info in it and just delete that line after it runs and populates the first time.

**Comment by DKrzewinski** [comment]
I've tried your suggestion to put a random line of info for the Tombstone.csv.
You are right it looks like it is this file that is causing an error.
After populating it though it comes up with an error:

Cannot convert value "@{Name=............." to type 
"System.Collections.ArrayList". Error: "Cannot convert the "@{Name=..." value of 
type "System.Management.Automation.PSCustomObject" to type "System.Collections.ArrayList"."
At C:\Tombstone\Secure\Tombstoning.ps1:28 char:1
+ [System.Collections.ArrayList]$global:LoggingCSV = Import-Csv $Loggin ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ArgumentTransformationMetadataException
    + FullyQualifiedErrorId : RuntimeException

Script finishes but the file is now empty. Any clues ?

**Comment by wsowe2** [comment]
interesting and i didn't catch it before. add at least 2 false data lines to the CSV and then run it. having it empty or with only a single line, it imports as either null or just a single pscustomobject. in order for it to be considered an "array" it needs to have at least 2 objects and then it can also be considered an arraylist. it should import without error. once you populate it with your own info, make sure to delete those first 2 entries. i have updated the Tombstone.csv file in the repo with a new one that should import without any issues. Also updated the BLKEY file with a dummy entry as well. delete the test entries when you have populated with your own info.

**Comment by DKrzewinski** [comment]
Looks like that worked just fine this time.
Very strange it needs some data for it to work instead of treating the file as an array but OK.
Thanks for your help!

**Comment by wsowe2** [comment]
you have to have multiple entries so it is considered an "array" which can be converted to an arraylist if needed. if you declare it as an empty arraylist, you'll get the "cannot call a method on a null-valued expression" when you try to use the ".add($Add)" and it will fail. having the multiple entries bypasses the null value and the inability to declare it as an arraylist. if i only used an array here, this would all be moot but i knew I would be adding and removing from it all thru the script, so i didn't want to tear down and rebuild that many arrays. i guess i could have just used a hashtable as well but this is just how i did it lol. glad it works with the new files.

**Comment by DKrzewinski** [comment]
Makes sense.
Thanks mate!
